const images = [
  { id: 0, img: "/images/Dark.jpg" },
  { id: 1, img: "/images/Dark1.jpg" },
  { id: 2, img: "/images/Dark2.jpg" },
  { id: 3, img: "/images/Dark3.jpg" },
  { id: 4, img: "/images/Dark4.jpg" },
  { id: 5, img: "/images/Dark5.jpg" },
  { id: 6, img: "/images/Dark6.jpg" },
  { id: 7, img: "/images/Dark7.jpg" },
  { id: 8, img: "/images/Dark8.jpg" },
  { id: 9, img: "/images/Dark9.jpg" },
  { id: 10, img: "/images/Light.jpg" },
  { id: 11, img: "/images/Light1.jpg" },
  { id: 12, img: "/images/Light2.jpg" },
  { id: 13, img: "/images/Light3.jpg" },
  { id: 14, img: "/images/Light4.jpg" },
  { id: 15, img: "/images/Light5.jpg" },
  { id: 16, img: "/images/Light6.jpg" },
  { id: 17, img: "/images/Light7.jpg" },
  { id: 18, img: "/images/Light8.jpg" },
  { id: 19, img: "/images/Light9.jpg" },
];
export default images